config/routes.rb
Rails.application.routes.draw do

  resources :employees
  resources :stores do
    get :send_admin_email
  end
  resources :companies do
    get :new_store
  end

  root 'application#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :stores, dependent: :destroy

  validates :name, :presence => true, :uniqueness => true

  accepts_nested_attributes_for :stores
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_and_belongs_to_many :stores, :uniq => true

  validates :email, :presence => true, :uniqueness => true
  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :stores, :presence => { :message => " - an employee must be associated with at least one store" }

  def full_name
    "#{first_name} #{last_name}"
  end

  def stores_count
    stores.count
  end
end

app/models/store.rb
class Store < ActiveRecord::Base
  belongs_to :company
  has_and_belongs_to_many :employees, :uniq => true

  validates :location_name, :presence => true, :uniqueness => true
  validates :company_id, :presence => true

  before_destroy :check_employees

  def company_name
    company.name
  end

  def send_admin_email
    StoreMailer.employee_list_email(self).deliver
    self.update_column(:last_admin_email, DateTime.now)
  end

  private

  def check_employees
    employees.each do |employee|
      if employee.stores_count == 1
        employee.destroy
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def index
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  # GET /companies
  def index
    @companies = Company.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /companies/1
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /companies/new
  def new
    @company = Company.new

    respond_to do |format|
      format.js
    end
  end

  def new_store
    @company = Company.find(params[:company_id])

    respond_to do |format|
      format.js
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  # POST /companies
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.js
      else
        format.html { redirect_to companies_url }
        format.js {
          render js: %Q{alert("#{@company.errors.full_messages.to_sentence}");}
        }
      end
    end
  end

  # PUT /companies/1
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.js
      else
        format.html { render action: "edit" }
        format.js {
          render js: %Q{alert("#{@company.errors.full_messages.to_sentence}");}
        }
      end
    end
  end

  # DELETE /companies/1
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.js
    end
  end

  private

  def company_params
    params.require(:company).permit(:name, stores_attributes: [:location_name])
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  # GET /employees
  def index
    @employees = Employee.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /employees/1
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /employees/new
  def new
    @employee = Employee.new

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  # POST /employees
  def create
    @employee = Employee.new(employee_params)
    if params[:store_ids]
      params[:store_ids].each do |id|
        store = Store.find(id.to_i)
        @employee.stores << store
      end
    end

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.js
      else
        format.html { render action: "new" }
        format.js {
          render js: %Q{alert("#{@employee.errors.full_messages.to_sentence}");}
        }
      end
    end
  end

  # PUT /employees/1
  def update
    @employee = Employee.find(params[:id])
    @employee.stores.clear
    if params[:store_ids]
      params[:store_ids].each do |id|
        store = Store.find(id.to_i)
        @employee.stores << store
      end
    end

    respond_to do |format|
      if @employee.update_attributes(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.js
      else
        format.html { render action: "edit" }
        format.js {
          render js: %Q{alert("#{@employee.errors.full_messages.to_sentence}");}
        }
      end
    end
  end

  # DELETE /employees/1
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url }
      format.js
    end
  end

  private

  def employee_params
    params.require(:employee).permit(:email, :first_name, :last_name)
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController

  # GET /stores
  def index
    @stores = Store.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /stores/1
  def show
    @store = Store.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /stores/new
  def new
    @store = Store.new

    respond_to do |format|
      format.js
    end
  end

  # GET /stores/1/edit
  def edit
    @store = Store.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  # POST /stores
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.js
      else
        format.html { redirect_to stores_url }
        format.js {
          render js: %Q{alert("#{@store.errors.full_messages.to_sentence}");}
        }
      end
    end
  end

  # PUT /stores/1
  def update
    @store = Store.find(params[:id])

    respond_to do |format|
      if @store.update_attributes(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.js
      else
        format.html { render action: "edit" }
        format.js {
          render js: %Q{alert("#{@store.errors.full_messages.to_sentence}");}
        }
      end
    end
  end

  # DELETE /stores/1
  def destroy
    @store = Store.find(params[:id])
    @store.destroy

    respond_to do |format|
      format.html { redirect_to stores_url }
      format.js
    end
  end

  def send_admin_email
    if params[:store_id]
      store = Store.find(params[:store_id])
      store.send_admin_email
    end

    respond_to do |format|
      format.html { redirect_to stores_url }
        format.js {
          render js: "alert('Email sent.');"
        }
    end
  end

  private

  def store_params
    params.require(:store).permit(:location_name, :company_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/application/index.html.erb
<h1>Hr test app</h1>
<p>Use the menu above.</p>

app/views/companies/_company.html.erb
<tr id="company_<%= company.id %>">
  <td><%= company.name %></td>
  <td><%= link_to 'Show', company %></td>
  <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure? This action will destroy all associated stores and possibly some employees.' }, remote: true %></td>
</tr>

app/views/companies/_form.html.erb
<%= form_for(@company, remote: true) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/_new_store_form.html.erb
<%= form_for(@company, remote: true) do |f| %>
  <%= f.fields_for :stores, @company.stores.build do |ff| %>
    <div class="field">
      <%= ff.label :location_name %><br />
      <%= ff.text_field :location_name %>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit "Create store" %>
  </div>
<% end %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table id="companies-list">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @companies.each do |company| %>
      <%= render company %>
    <% end %>
  </tbody>
</table>

<br />

<div id="new-company-wrapper">
  <%= link_to 'New Company', new_company_path, id: "new-company-link", remote: true %>
</div>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @company.name %>
</p>

<p><b>Stores:</b></p>
<ul id="stores-list">
  <% @company.stores.each do |store| %>
    <li id="store_<%= store.id %>"><%= link_to store.location_name, store %> (<%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure? This action might destroy some of the associated employees.' }, remote: true %>)</li>
  <% end %>
</ul>

<div id="new-store-wrapper"></div>

<%= link_to 'Create & add a new store', company_new_store_path(@company), id: "new-store-link", remote: true %><br />
<%= link_to 'Back', companies_path %>

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <p>Stores:</p>
  <% if Store.count == 0 %>
    <p>There are no stores in the database. Please, create at least one.</p>
  <% else %>
    <% Store.all.each do |store| %>
      <%= check_box_tag "store_ids[#{store.id}]", store.id, @employee.stores.include?(store) ? true : false, name: "store_ids[]" %>
      <%= label_tag "store_ids[#{store.id}]", store.location_name %>
    <% end %>
  <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Listing employees</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>No. of Stores</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @employees.each do |employee| %>
      <tr id="employee_<%= employee.id %>">
        <td><%= employee.first_name %></td>
        <td><%= employee.last_name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.stores_count %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' }, remote: true %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @employee.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @employee.last_name %>
</p>

<p>
  <b>Email:</b>
  <%= @employee.email %>
</p>

<p><b>Stores:</b></p>
<ul>
  <% @employee.stores.each do |store| %>
    <li><%= link_to store.location_name, store %></li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_employee_path(@employee) %><br />
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HrApp</title>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <ul>
        <li><%= link_to "Main page", root_path %></li>
        <li><%= link_to "Companies list", companies_path %></li>
        <li><%= link_to "Stores list", stores_path %></li>
        <li><%= link_to "Employees list", employees_path %></li>
      </ul>
    </header>

    <div id="content">
      <%= yield %>
    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location_name %><br />
    <%= f.text_field :location_name %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br />
    <%= f.select :company_id, options_from_collection_for_select(Company.all, 'id', 'name', @store.company_id) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stores/_form_remote.html.erb
<%= form_for(@store, remote: true) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location_name %><br />
    <%= f.text_field :location_name %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br />
    <%= f.select :company_id, options_from_collection_for_select(Company.all, 'id', 'name') %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stores/_store.html.erb
<tr id="store_<%= store.id %>">
  <td><%= store.location_name %></td>
  <td><%= link_to store.company_name, store.company %></td>
  <td><%= store.employees.count %></td>
  <td><%= link_to 'Send admin an email', store_send_admin_email_path(store.id), remote: true %></td>
  <td><%= link_to 'Show', store %></td>
  <td><%= link_to 'Edit', edit_store_path(store) %></td>
  <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure? This action might destroy some of the associated employees.' }, remote: true %></td>
</tr>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= render 'form' %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<h1>Listing stores</h1>

<table id="stores-list">
  <thead>
    <tr>
      <th>Location name</th>
      <th>Company</th>
      <th>No. of Employees</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @stores.each do |store| %>
      <%= render store %>
    <% end %>
  </tbody>
</table>

<br />

<div id="new-store-wrapper">
<%= link_to 'New Store', new_store_path, id: "new-store-link", remote: true %>
</div>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Location name:</b>
  <%= @store.location_name %>
</p>

<p>
  <b>Company:</b>
  <%= link_to @store.company_name, @store.company %>
</p>

<p>
  <b>Last admin email sent:</b>
  <%= @store.last_admin_email || "never" %>
</p>

<p><b>Employees (<%= @store.employees.count %> in total):</b></p>
<ul id="employees-list">
  <% @store.employees.each do |e| %>
    <li><%= link_to e.full_name, e %> (<%= e.email %>)</li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_store_path(@store) %><br />
<%= link_to 'Back', stores_path %>